

stages:
  - package
  - publish
  - test

.package: &package
  image: $CI_REGISTRY/docker-images/layers:jessie-deb
  stage: package
  script:
    - echo "deb http://symbiosis.bytemark.co.uk/jessie/ ./" >> /etc/apt/sources.list
    - apt-get update
    - export PACKAGE=${CI_BUILD_NAME##package:}
    - echo "$CI_BUILD_NAME" -  "$PACKAGE" - "${CI_BUILD_NAME##package:}"
    - cd $PACKAGE
    - package
  artifacts:
    paths:
      - pkg/

package:common:
  <<: *package
package:backup:
  <<: *package
package:cron:
  <<: *package
package:dns:
  <<: *package
package:doc:
  <<: *package
package:email:
  <<: *package
package:firewall:
  <<: *package
package:ftpd:
  <<: *package
package:httpd:
  <<: *package
package:httpd-logger:
  <<: *package
package:meta:
  <<: *package
package:monit:
  <<: *package
package:mysql:
  <<: *package
package:phpmyadmin:
  <<: *package
package:updater:
  <<: *package
package:webmail:
  <<: *package
package:xmpp:
  <<: *package

publish:
  stage: publish
  variables:
    RSYNC_HOSTNAME: repo.bytemark.co.uk
  tags:
    - shell
  script:
    - publish

.test: &test
  stage: test
  image: $CI_REGISTRY/docker-images/base:jessie
  tags:
    - kvm
  variables:
    VERBOSE: --verbose
    HOSTNAME: testing.example.com
  script:
    - rm -fv /usr/sbin/policy-rc.d
    - cd autotest
    - echo ${CI_BUILD_NAME##test:} > test.d/conf/action
    - "echo deb http://repo.bytemark.co.uk/symbiosis/$CI_BUILD_REF_SLUG/$CI_PIPELINE_ID/ ./ >> test.d/conf/maker-sources.list"
    - run-parts $VERBOSE --new-session --exit-on-error $PWD/test.d 

test:dist-upgrade:
  <<: *test
  image: $CI_REGISTRY/docker-images/base:wheezy

test:upgrade:
  <<: *test

test:fresh-install:
  <<: *test


