stages:
  - test
  - package
  - publish
  - install

.test: &test
  stage: test
  image: $CI_REGISTRY/docker-images/layers:stretch-ruby
  script:
    - adduser --home=/srv --shell=/bin/bash --no-create-home --disabled-login --gecos='Symbiosis Administrator,,,' admin
    - chown admin.admin /srv
    - cp autotest/test.d/conf/autotest-sources.list /etc/apt/sources.list.d/
    - "[ -z \"$TEST_DEPS\" ] || (apt-get update ; apt-get install $TEST_DEPS)"
    - export PACKAGE=${CI_BUILD_NAME##test:}
    - cd $PACKAGE
    - "[ ! -f Makefile ] || make test"

test:backup:
  <<: *test

test:common:
  variables:
    TEST_DEPS: ruby ruby-acme-client ruby-linux-netlink ruby-cracklib ruby-erubis ruby-mocha ruby-webmock ruby-test-unit openssl cracklib-runtime
  <<: *test

test:cron:
  <<: *test

test:dns:
  variables:
    TEST_DEPS: ruby-linux-netlink ruby-erubis
  <<: *test

test:doc:
  <<: *test

test:email:
  variables:
    TEST_DEPS: exim4-daemon-heavy dovecot-common dovecot-core dovecot-sieve dovecot-managesieved dovecot-imapd dovecot-pop3d ruby-linux-netlink ruby-eventmachine ruby-cracklib cracklib-runtime ruby-mocha
  <<: *test

test:firewall:
  variables:
    TEST_DEPS: ruby-linux-netlink ruby-sqlite3 netbase iptables
  <<: *test

test:ftpd:
  variables:
    TEST_DEPS: ruby-linux-netlink
  <<: *test

test:httpd:
  variables:
    RUBYOPT: -v
    TEST_DEPS: ruby-linux-netlink ruby-erubis apache2
  <<: *test

test:httpd-logger:
  variables:
    TEST_DEPS: golang-go ruby-linux-netlink
  <<: *test

test:meta:
  <<: *test

test:monit:
  variables:
    TEST_DEPS: ruby-sqlite3 ruby-log4r
  <<: *test

test:mysql:
  <<: *test

test:phpmyadmin:
  <<: *test

test:updater:
  <<: *test

test:webmail:
  <<: *test

test:xmpp:
  <<: *test

.package: &package
  image: $CI_REGISTRY/docker-images/layers:stretch-deb
  stage: package
  script:
    - export PACKAGE=${CI_BUILD_NAME##package:}
    - echo "$CI_BUILD_NAME" -  "$PACKAGE" - "${CI_BUILD_NAME##package:}"
    - cd $PACKAGE
    - package
  artifacts:
    paths:
      - pkg/

package:common:
  <<: *package
package:backup:
  <<: *package
package:cron:
  <<: *package
package:dns:
  <<: *package
package:doc:
  <<: *package
package:email:
  <<: *package
package:firewall:
  <<: *package
package:ftpd:
  <<: *package
package:httpd:
  <<: *package
package:httpd-logger:
  <<: *package
package:meta:
  <<: *package
package:monit:
  <<: *package
package:mysql:
  <<: *package
package:phpmyadmin:
  <<: *package
package:updater:
  <<: *package
package:webmail:
  <<: *package
package:xmpp:
  <<: *package

publish:
  stage: publish
  variables:
    RSYNC_HOSTNAME: repo.bytemark.co.uk
  tags:
    - shell
  script:
    - publish

# fails on stretch for the time being - see issue #57 for updates
.install: &install
  stage: install
  tags:
    - systemd-containers
  before_script:
    - set -x
    - MACHINE=symbiosis-$DEBIAN_RELEASE-$ACTION-$CI_BUILD_ID
    - RUN_ARGS="--wait --quiet --pty --machine $MACHINE"
    - |
      if [ "$ACTION" = "install" ]; then
        machinectl clone ${DEBIAN_RELEASE} $MACHINE
      else
        machinectl clone ${OLD_DEBIAN_RELEASE} $MACHINE
      fi
    - machinectl start $MACHINE
    - sleep 10
    - machinectl copy-to $MACHINE test/internal-test.d /root/test.d
  script:
    - | 
      cat > /var/lib/machines/$MACHINE/run-test <<TEST
      #!/bin/bash
      
      set -x

      ACTION=$ACTION
      DEBIAN_RELEASE=$DEBIAN_RELEASE
      OLD_DEBIAN_RELEASE=$OLD_DEBIAN_RELEASE
      BRANCH_NAME=$CI_BUILD_REF_SLUG
      
      /bin/run-parts --exit-on-error /root/test.d/
    - chmod +x /var/lib/machines/$MACHINE/run-test
    - export IP=$(get-machine-ip $MACHINE)
    - ssh root@IP /run-test
    - run-parts --exit-on-error test/external-test.d
  after_script:
    - MACHINE=symbiosis-$DEBIAN_RELEASE-$ACTION-$CI_BUILD_ID
    - machinectl poweroff $MACHINE || true
    - sleep 10
    - machinectl remove $MACHINE
  variables: &installvars
    DEBIAN_RELEASE: stretch
    OLD_DEBIAN_RELEASE: jessie

install:dist-upgrade:
  <<: *install
  variables:
    <<: *installvars
    ACTION: dist-upgrade

install:upgrade:
  <<: *install
  variables:
    <<: *installvars
    ACTION: upgrade

install:fresh-install:
  <<: *install
  variables:
    <<: *installvars
    ACTION: install


